name: Build, Lint and Test

on:
  pull_request:

jobs:
  unit-test:
    name: Build, Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.3.0'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm run test
